name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to RunPod registry
        uses: docker/login-action@v3
        with:
          registry: registry.runpod.net
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.RUNPOD_TOKEN }}

      - name: Log in to RunPod registry
        uses: docker/login-action@v3
        with:
          registry: registry.runpod.net
          username: ${{ jessifay.art }}
          password: ${{ Runb0yRunfromthesun! }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: astroblimp/runpod-comfyui-qwen:qwen-tts
